### ISSUE TITLE
end-to-end testing pipeline/tooling for metachain

### ISSUE THREAD

**Issue by fuxingloh** [DeFiCh/metachain#11]
#### What would you like to be added:

At `JellyfishSDK/jellyfish`, there was a strong use of Containers + Javascript-based API for end-to-end (e2e) testing of services. Similarly, we need something like that here. Not to confuse integration or unit with e2e, e2e tests the resulting artifacts, and the entire artifact/binary lifecycle from start to finish. Hence it might not make sense to do it in Rust?

> #### Unit Tests
> The purpose of unit tests is to test each unit of code in isolation from the rest of the code to quickly pinpoint where code is and isn’t working as expected. You’ll put unit tests in the src directory in each file with the code that they’re testing. The convention is to create a module named tests in each file to contain the test functions and to annotate the module with cfg(test).
> #### Integration Tests
> In Rust, integration tests are entirely external to your library. They use your library in the same way any other code would, which means they can only call functions that are part of your library’s public API. Their purpose is to test whether many parts of your library work together correctly. Units of code that work correctly on their own could have problems when integrated, so test coverage of the integrated code is important as well. To create integration tests, you first need a tests directory.
>
> https://doc.rust-lang.org/book/ch11-03-test-organization.html

#### Why is this needed:

Quality.

/triage accepted
/area workflow

**Comment by surangap** [comment]
My idea about testing

- `Unit testing` and `Integration testing` Can be done in Rust with the help of mockers when required.
- For `e2e testing` we definitely should have a setup where we run a native node and DMC node and check the test scenarios in between. In Jellyfish, it was between the SDK and the native node. Here we have two nodes. so it could be
  - running both native and DMC nodes with docker
  - a set of tests calling endpoints provided by both nodes to test scenarios. The tests could be written in any suitable language.
  - If we use another language it would be like the python test framework on the CPP side. one thing that should be noted is that if some functionality is required in the testing, had to implement it again in python even though it's already available in the CPP code. 
  - In Jellyfish, we had some advantages since the SDK and testing were both done in TS. We could have the same in here as well, means testing also in Rust. for example, we could reuse the code from DMC packages in the test code as well for signing, verification, etc... will have to write some boilerplate code for the testing framework 😛 as we did with Jellyfish testing. But have to think about the advantages of having e2e in Rust if it does not take much effort 🤔

**Comment by fuxingloh** [comment]
But I think from an e2e testing perspective, using the same module to generate the stub (e.g. tx-hex) and sending the stub to the internals would not effectively test anything meaningful since the stub generated comes from the same module as the internal. It is checking itself in this case `a() == a()`.

🤔

**Comment by surangap** [comment]
I did not mean it that way. Definitely, the functions reused from the test subject(DMC modules) should be out of the test scope of the current test. more like supporting functions that have been already verified by another set of tests. like the way we do in Jellyfish tests. But when it comes to e2e testing occurrence of such situations might be lesser.

**Comment by fuxingloh** [comment]
Haha, just food for thought, I do agree with your points. I guess my comment is more of a mental struggle for the uninitiated to differentiate the testing scopes and their intent. That being said, I think Rust modules system to control scope and privacy  is well equipped to handle testing scope pollution.

**Comment by fuxingloh** [comment]
One of the considerations I'm thinking about is also the ease of testing for the "uninitiated". Not having to worry about the complexity of borrow checker. (Altho that being said, within e2e testing scope, there isn't much need for pointer passing when you're testing code.)
