### ISSUE TITLE
Github workflows to utilize building on docker engine

### ISSUE THREAD

**Issue by DieHard073055** [DeFiCh/metachain#61]
#### What would you like to be added:

Builds should use docker `qemu` + `buildx`.
Building on docker engine will allow us to utilize qemu.

#### Why is this needed:
To make the builds as OS agnostic as possible.

[Reference Conversation](https://github.com/DeFiCh/metachain/pull/43#discussion_r959349664)

**Comment by mambisi** [comment]
@fuxingloh  cd.yml on this https://github.com/DeFiCh/metachain/blob/c0820458c0bad868dd36a495045ca24460cc5873/.github/workflows/cd.yml
already build with `qemu` `buildx`

**Comment by fuxingloh** [comment]
> @fuxingloh cd.yml on this https://github.com/DeFiCh/metachain/blob/c0820458c0bad868dd36a495045ca24460cc5873/.github/workflows/cd.yml already build with `qemu` `buildx`

The setup and build are done on the GitHub workflow host instance via:

https://github.com/DeFiCh/metachain/blob/cb6307db169f6b58551cb3dd986277fe7bdbe1a4/.github/workflows/release-docker.yml#L19

with this build and run step:

https://github.com/DeFiCh/metachain/blob/cb6307db169f6b58551cb3dd986277fe7bdbe1a4/.github/workflows/release-docker.yml#L36-L49

the binary is then copied into a Docker Image via:

https://github.com/DeFiCh/metachain/blob/cb6307db169f6b58551cb3dd986277fe7bdbe1a4/.github/workflows/release-docker.yml#L51-L54

and

https://github.com/DeFiCh/metachain/blob/cb6307db169f6b58551cb3dd986277fe7bdbe1a4/Dockerfile#L5-L6

---

This issue was created to move the build process into Docker Engine with `qemu` and `buildx`. Since we're now building on host imagine instead of a Docker multi-arch engine: https://www.docker.com/blog/multi-arch-images/

**Comment by mambisi** [comment]
okay got it

**Comment by fuxingloh** [comment]
> okay got it 

I'm not too familiar with Cargo build. Since for other languages, you need to build on the same OS/target to run on the same target arch/env. Or generally that's how it's done afaik

I will defer to you to make this decision, it might not warrant or require it. If you think otherwise just drop a note here with the explanation, I will close this issue.
