### ISSUE TITLE
Reserve `1130` for `chainlist.org`, `ss58`, and `slip-0044`

### ISSUE THREAD

**Issue by canonbrother** [DeFiCh/metachain#75]
#### What would you like to be added:
Add `mainnet` and `testnet` address prefixes

Where to add -> https://github.com/paritytech/ss58-registry

#### Why is this needed:
The address prefix that identifies an address as belonging to a specific network.

**Comment by fuxingloh** [comment]
Blocked by: 
- #69  
- #72

**Comment by fuxingloh** [comment]
Let me re-assign this to @weiyuan95 to help with his. Can you help us add `chainId` and `cointype` into various registries:
- https://github.com/satoshilabs/slips/blob/master/slip-0044.md
- https://github.com/paritytech/ss58-registry/blob/main/ss58-registry.json
- https://github.com/ethereum-lists/chains/blob/master/_data/chains/eip155-1.json

---

Our slip-44 coinType `1129` is `0x80000469`, which is `(D=4,F=6,I=9)`

Let's use `1130` since it's one away from `1129`, and it isn't taken.

- CoinType/Prefix/ChainId: `1130`
- Network: `defichain`
- DisplayName: `DeFiChain Network`
- Symbol: `DFI`
- Decimals: `18`
- Website: `https://meta.defichain.com`

**Comment by weiyuan95** [comment]
slip-0044: https://github.com/satoshilabs/slips/pull/1451

**Comment by weiyuan95** [comment]
ss-58: https://github.com/paritytech/ss58-registry/pull/145 , added for both main and test net.

**Comment by weiyuan95** [comment]
chainlist: https://github.com/ethereum-lists/chains/pull/1911 , added for both main and test net.

**Comment by weiyuan95** [comment]
There probably needs to be a follow up issue to update the chainlist repository with RPC / faucet / explorer etc. urls once those are ready.

**Comment by fuxingloh** [comment]
Closing this, as 2/3 are merged. IMO it's as good as reserved
